name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  def-input:  # id of input
    description: 'default value set to github.token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
