name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  sample-env-var:  # id of input
    description: 'A sample env var'
    required: false
    default: 'Value'
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
  defnreq:
    description: 'Def nreq value'
    default: 'Val nreq'
    required: false
  defno:
    description: 'Def no value'
    default: 'Val no'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
