on: [push]

jobs:
  no_bool_input:
    runs-on: ubuntu-latest
    name: No bool input
    steps:
      - name: create env
        run: |
          echo "cache=$(go env GOCACHE)" >> $GITHUB_ENV

      - name: use end
        run: |
          echo "cache=${{ env.cache }}"
