on: [push]

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: read

jobs:
  no_bool_input:
    runs-on: ubuntu-latest
    name: No bool input
    steps:
      - name: Hello world action step
        id: hello
        uses: akv-demo/custom-action@input
        # with:
        #  def-input: ${{ secrets.BASIC_TOKEN }}

      - name: use output
        env:
          GITHUB_TOKEN: ${{ steps.hello.outputs.defoutput }}
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/akv-demo/custom-action/issues/1/comments -d "{\"body\":\"$(date)\"}"

