on: [push]

jobs:
  no_bool_input:
    runs-on: ubuntu-latest
    name: No bool input
    steps:
      - name: Hello world action step
        id: hello
        uses: akv-demo/custom-action@input
      #  with:
      #    who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output
        run: |
          echo "The DefOutput is ${{ steps.hello.outputs.DefOutput }}"
          echo "The defoutput is ${{ steps.hello.outputs.defoutput }}"
          echo "The def_output is ${{ steps.hello.outputs.def_output }}"
